type Row = Record<string, any>;

function escapeHtml(value: any) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function renderTable(content: Row) {
  return `
    <table class="evidence-table">
      <tbody>
        ${Object.entries(content || {})
          .map(
            ([key, value]) => `
              <tr>
                <td class="key">${escapeHtml(key)}</td>
                <td class="value">${escapeHtml(
                  typeof value === "object"
                    ? JSON.stringify(value, null, 2)
                    : value
                )}</td>
              </tr>
            `
          )
          .join("")}
      </tbody>
    </table>
  `;
}

function renderJson(content: any) {
  return `
    <pre class="json-block">${escapeHtml(
      JSON.stringify(content, null, 2)
    )}</pre>
  `;
}

export function generateEvidencePdfHtml(model: Row) {
  const sectionsHtml = (model.sections || [])
    .map((section: Row) => {
      let body = "";

      if (section.kind === "table") {
        body = renderTable(section.content);
      } else if (section.kind === "json") {
        body = renderJson(section.content);
      } else {
        body = `<div>${escapeHtml(
          JSON.stringify(section.content, null, 2)
        )}</div>`;
      }

      return `
        <section class="section">
          <h2>${escapeHtml(section.title)}</h2>
          ${body}
        </section>
      `;
    })
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />

<title>HMRC Forensic Evidence Pack</title>

<style>
body {
  font-family: Arial, sans-serif;
  padding: 40px;
  color: #111827;
  background: #ffffff;
}

h1 {
  font-size: 28px;
  margin-bottom: 8px;
}

h2 {
  margin-top: 32px;
  margin-bottom: 16px;
  font-size: 20px;
  border-bottom: 1px solid #e5e7eb;
  padding-bottom: 8px;
}

.meta {
  margin-bottom: 24px;
  color: #475569;
}

.section {
  margin-bottom: 32px;
  page-break-inside: avoid;
}

.evidence-table {
  width: 100%;
  border-collapse: collapse;
}

.evidence-table td {
  border: 1px solid #e5e7eb;
  padding: 10px;
  vertical-align: top;
}

.key {
  width: 240px;
  font-weight: bold;
  background: #f8fafc;
}

.value {
  word-break: break-word;
}

.json-block {
  background: #0f172a;
  color: #e2e8f0;
  padding: 16px;
  border-radius: 8px;
  overflow-x: auto;
  white-space: pre-wrap;
  word-break: break-word;
  font-size: 12px;
}

.footer {
  margin-top: 60px;
  border-top: 1px solid #e5e7eb;
  padding-top: 16px;
  color: #64748b;
  font-size: 12px;
}
</style>
</head>

<body>

<h1>HMRC Forensic Evidence Pack</h1>

<div class="meta">
  <div><strong>Snapshot:</strong> ${escapeHtml(model.snapshotId)}</div>
  <div><strong>Generated:</strong> ${escapeHtml(model.generatedAt)}</div>
  <div><strong>Environment:</strong> ${escapeHtml(model.environment)}</div>
  <div><strong>Submission Type:</strong> ${escapeHtml(model.submissionType)}</div>
  <div><strong>Risk Level:</strong> ${escapeHtml(model.riskLevel)}</div>
</div>

${sectionsHtml}

<div class="footer">
  Immutable forensic evidence export generated by Hala Digital MTD ITSA platform.
</div>

</body>
</html>
  `;
}